# Generated by Django 4.1.7 on 2023-03-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="name",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
