# Generated by Django 4.1.7 on 2023-03-13 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="copy",
            old_name="is_available",
            new_name="is_avaliable",
        ),
    ]
