# Generated by Django 4.1.7 on 2023-03-15 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
